---
language: rust
dist: trusty
sudo: required

matrix:
  include:
    - rust: stable
      addons:
        apt:
          packages:
            # cargo-tarpaulin needs this
            - libssl-dev
      install:
        # For test coverage. In install step so that it can use cache.
        - cargo tarpaulin --version || cargo install cargo-tarpaulin
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - 'if [[ "$TRAVIS_RUST_VERSION" = nightly ]]; then cargo bench; fi'

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" = stable ]]; then
    # Calculate test coverage
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
